### ISSUE TITLE
gemfile gems order affects boot

### ISSUE THREAD

**Issue by masciugo** [ianheggie/health_check#89]
with this:
```
gem 'health_check'
gem 'active_model_serializers', '~> 0.10.0'
```
I got 
```
Bundler::GemRequireError: There was an error while trying to load the gem 'health_check'.
Gem Load Error is: uninitialized constant HealthCheck::ActionController
Backtrace for gem load error is:
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:76:in `block in load_missing_constant'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:76:in `rescue in load_missing_constant'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `load_missing_constant'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/health_check-3.0.0/lib/health_check/health_check_controller.rb:5:in `<module:HealthCheck>'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/health_check-3.0.0/lib/health_check/health_check_controller.rb:4:in `<main>'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/health_check-3.0.0/lib/health_check.rb:88:in `<main>'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/Users/foo/dev/cohort_genomics/osr_people/config/application.rb:18:in `<main>'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
/Users/foo/dev/cohort_genomics/osr_people/Rakefile:4:in `<main>'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load_rakefile'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:703:in `raw_load_rakefile'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:104:in `block in load_rakefile'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:103:in `load_rakefile'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:82:in `block in run'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/foo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
bin/rake:4:in `<main>'
Bundler Error Backtrace:
/Users/foo/dev/cohort_genomics/osr_people/config/application.rb:18:in `<main>'
/Users/foo/dev/cohort_genomics/osr_people/Rakefile:4:in `<main>'

Caused by:
NameError: uninitialized constant HealthCheck::ActionController
/Users/foo/dev/cohort_genomics/osr_people/config/application.rb:18:in `<main>'
/Users/foo/dev/cohort_genomics/osr_people/Rakefile:4:in `<main>'

Caused by:
NameError: uninitialized constant HealthCheck::ActionController
/Users/foo/dev/cohort_genomics/osr_people/config/application.rb:18:in `<main>'
/Users/foo/dev/cohort_genomics/osr_people/Rakefile:4:in `<main>'
```
while swapping the two gems it boots:
```
gem 'active_model_serializers', '~> 0.10.0'
gem 'health_check'
```

**Comment by shlima** [comment]
@masciugo you can check an [alternative](https://github.com/shlima/health_bit)

**Comment by ianheggie** [comment]
@masciugo - for the time being, just include your rails components first; rails new generates the Gemfile with rails at the top.

I require railties in the gemspec, but it looks like that no longer drags in the actual requirements (probably when api only generator was added). 

[Not helpful in this case shlima]

**Comment by ianheggie** [comment]
Documented order in Gemfile in version 3.1.0 released just now
